# Generated by Django 2.1.5 on 2019-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpArcApp', '0003_auto_20190327_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(default='/skills_pics', upload_to='skills_pics/'),
        ),
    ]
