# Generated by Django 2.1.5 on 2019-03-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190327_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
