# Generated by Django 2.1.5 on 2019-03-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_titleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='titleId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HelpArcApp.Title'),
        ),
    ]
