# Generated by Django 2.1.5 on 2019-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190327_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountLevel',
            field=models.IntegerField(default=0),
        ),
    ]
